#!/usr/bin/env ruby
require 'json'
require 'time'
require 'pp'

sha = `git rev-parse HEAD`.strip
tag = "v%s" % File.read(File.expand_path('../../VERSION', __FILE__)).strip
token = ENV.fetch('GITHUB_TOKEN')
repo  = ENV.fetch('TRAVIS_REPO_SLUG')

cmd = "curl --silent -X POST https://api.travis-ci.org/auth/github?github_token=#{token}"
result = `#{cmd}`
travis_token = JSON(result)['access_token']

cmd = "curl --silent -H \"Authorization: token %{token}\" https://api.travis-ci.org/repos/%{repo}/builds?ids=%{id}" % {
  id: ENV.fetch('TRAVIS_BUILD_ID'),
  token: travis_token,
  repo: repo,
}
result = `#{cmd}`
unless JSON(result).first['state'] == 'finished'
  puts "Build not yet finished"
  exit 1
end

cmd = "curl -H \"Authorization: token %{token}\" -XPOST https://api.github.com/repos/%{repo}/git/refs -d '%{json}'" % {
  token: token,
  repo: repo,
  json: JSON(
    ref: "refs/tags/#{tag}",
    sha: sha,
  )
}
unless system cmd
  puts "Failed"
  exit 1
end

json = JSON(
  tag: tag,
  object: sha,
  type: "commit",
  tagger: {
    name: `git config user.name`.strip,
    email: `git config user.email`.strip,
    date: Time.now.iso8601,
  }
)

cmd = "curl -H \"Authorization: token %{token}\" -XPOST https://api.github.com/repos/%{repo}/git/tags -d '%{json}'" % {
  token: token,
  repo: repo,
  json: json,
}
system cmd
